require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/settlements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Settlement. As you add validations to Settlement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Settlement.create! valid_attributes
      get settlements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      settlement = Settlement.create! valid_attributes
      get settlement_url(settlement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_settlement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      settlement = Settlement.create! valid_attributes
      get edit_settlement_url(settlement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Settlement" do
        expect {
          post settlements_url, params: { settlement: valid_attributes }
        }.to change(Settlement, :count).by(1)
      end

      it "redirects to the created settlement" do
        post settlements_url, params: { settlement: valid_attributes }
        expect(response).to redirect_to(settlement_url(Settlement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Settlement" do
        expect {
          post settlements_url, params: { settlement: invalid_attributes }
        }.to change(Settlement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post settlements_url, params: { settlement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested settlement" do
        settlement = Settlement.create! valid_attributes
        patch settlement_url(settlement), params: { settlement: new_attributes }
        settlement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the settlement" do
        settlement = Settlement.create! valid_attributes
        patch settlement_url(settlement), params: { settlement: new_attributes }
        settlement.reload
        expect(response).to redirect_to(settlement_url(settlement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        settlement = Settlement.create! valid_attributes
        patch settlement_url(settlement), params: { settlement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested settlement" do
      settlement = Settlement.create! valid_attributes
      expect {
        delete settlement_url(settlement)
      }.to change(Settlement, :count).by(-1)
    end

    it "redirects to the settlements list" do
      settlement = Settlement.create! valid_attributes
      delete settlement_url(settlement)
      expect(response).to redirect_to(settlements_url)
    end
  end
end
